contracts/LivepeerProtocol.sol
test/LivepeerProtocol.js

Addresses #20 and #21 
- Introduce variables representing pending values for `blockRewardCut`, `feeShare` and `pricePerSegment`
- Pending transcoder information values are set as current transcoder information values when `setCurrentActiveTranscoders()` is called

Transcoder job params + pending transcoder information

---

contracts/LivepeerProtocol.sol
test/LivepeerProtocol.js

Addresses #22 
- `job()` function to create a new `Job` struct
- `electCurrentActiveTranscoder(_maxPricePerSegment)` is used to pseudorandomly select a current active transcoder with an acceptable price per segment
- `transcoderOptions` is currently a `bytes32` with encoding semantics to be determined at a later point in time

job() function and Job struct

---

.gitignore
contracts/LivepeerProtocol.sol
contracts/TranscodeJobs.sol
package.json
parseArtifacts.js
test/LivepeerProtocol.js

Changes the streamId type from `uint256` to `string` since the LP node represents a streamId as a string.
Also included some small changes for developing the Go client

Change stream id type

---

contracts/jobs/JobsManager.sol
contracts/verification/IdentityVerifier.sol
contracts/verification/Verifiable.sol
contracts/verification/Verifier.sol
migrations/2_deploy_contracts.js
test/LivepeerProtocolIntegration.js
test/jobs/JobsManager.js

Addresses #27 
Things to note:
- We will need to keep track of how many failed verifications a transcoder has. One option is to update the state of a transcoder in `BondingManager` from `JobsManager`. Another option is to keep track of failed verifications separately in a `VerificationManager` which might handle state for verification and slashing. I lean toward the latter at the moment since it isolates verification logic, but will explore more as we implement a non-trivial `Verifier` contract (i.e. Oraclize) that will actually return `false` for failed verifications.

Verification interface with IdentityVerifier

---

contracts/bonding/BondingManager.sol
contracts/bonding/libraries/TranscoderPools.sol
migrations/3_deploy_contracts.js
test/bonding/BondingManager.js

Added an array to keep track of addresses of all registered transcoders so a client can iterate through the array to retrieve addresses and then use the addresses to get transcoder stats from the `transcoders` map.
Also, defaulting to deploying with the `IdentityVerifier` for all networks for the time being until `OraclizeVerifier` + IPFS node integration is ready.

Keep track of all registered transcoders

---

contracts/bonding/BondingManager.sol
test/LivepeerProtocolIntegration.js
test/bonding/BondingManager.js
utils/bn_util.js

A spike to see how the code looks when transcoder candidacy is separated from delegation - opening PR to get some eyes on the structure, not meant to be considered for a merge yet. There are no updated tests yet.
- `bond` can be called on anyone
- If a user bonds to himself and calls `transcoder`, we try to add the user to the transcoder pools with his delegated stake. If a user is _not_ bonded to himself and calls `transcoder`, we try to add the user to the transcoder pools with 0 stake
- If a user resigns as a transcoder, he enters the `Resigned` state and the `delegatorWithdrawRound` field is set. When `delegatorWithdrawRound` is now or in the past, the user enters the `NotRegistered` state. A user can only re-register as a transcoder if he is in the `NotRegistered` state. This is to …

Separating transcoder candidacy from delegation

---

contracts/jobs/JobsManager.sol
contracts/test/JobsManagerMock.sol
contracts/test/VerifierMock.sol
contracts/verification/IVerifier.sol
contracts/verification/IdentityVerifier.sol
contracts/verification/LivepeerVerifier.sol
contracts/verification/OraclizeVerifier.sol
test/jobs/JobsManager.js
truffle.js
verification_test/OraclizeVerifier.js

Previously, a verifier contract did not check if the dataHash submitted by a transcoder matches the data located at the dataStorageHash submitted. Now the off-chain computation (Oraclize, an off-chain solver, etc.) will download `data` using the dataStorageHash, and submit back on-chain `keccak256(keccak256(data),transcodedDataHash)`. The verifier contract will compare this result with `keccak256(dataHash,transcodedDataHash)` where `dataHash` and `transcodedDataHash` are submitted by the transcoder, which is defined as the commit hash. If the transcoder provides a `dataStorageHash` that does not contain the data that matches `dataHash`, then this check will fail.

Verifier checks commit hash defined as h(dataHash,transcodedDataHash)

---

contracts/jobs/JobsManager.sol
contracts/jobs/libraries/JobLib.sol
test/jobs/JobsManager.js
utils/videoProfile.js

- Video profile identifiers calculated as `bytes4(keccak256(PROFILE_NAME))`
- We keep `transcodingOptions` as a string so the identifiers can be easily parsed by the Docker application that Oraclize passes the string to as a parameter
- Since we keep `transcodingOptions` as a utf8 encoded string, we actually use 8 bytes to store the utf8 encoded representation of the first 4 bytes of the keccak hash of a video profile name (4 bytes  * 2 characters per byte)
Fixes #78

Calculate fees based on number of video profiles

---

contracts/bonding/BondingManager.sol
contracts/bonding/IBondingManager.sol
contracts/bonding/libraries/TokenPools.sol
contracts/jobs/JobsManager.sol
contracts/rounds/RoundsManager.sol
contracts/test/BondingManagerMock.sol
contracts/test/JobsManagerMock.sol
contracts/test/MinterMock.sol
contracts/test/RoundsManagerMock.sol
contracts/token/IMinter.sol
contracts/token/Minter.sol
migrations/2_deploy_libraries.js
migrations/4_deploy_faucet.js
migrations/5_init_protocol.js
package.json
test/bonding/BondingManager.js
test/jobs/JobsManager.js
test/token/Minter.js
truffle.js

This is an implementation of a solution to our current gas limit vulnerabilities in looping through rounds to update a delegator's stake and looping through claims within a round to update a delegator's stake with fees that the delegator is eligible for.
This PR includes:
- Fees are paid out unbonded. Delegators claim their fee shares from fee pools during the rounds since their lastClaimTokenPoolsShareRound
- Transcoders claim their blockRewardCut and feeShare when they claim their reward and fee shares from token pools during the rounds since their lastClaimTokenPoolsShareRound as a delegator
- Transcoders calculate unclaimable fees and rewards when adding rewards and fees to token pools. The unclaimable fees and rewards go to a redistribution pool managed by the Minter
- When …

Unbonded fee payouts + delayed computation of transcoder bonded/unbonded amounts

---

contracts/ManagerProxy.sol
contracts/bonding/BondingManager.sol
contracts/jobs/JobsManager.sol
contracts/test/ManagerProxyTargetMockV1.sol
package.json
test/ManagerProxy.js
test/bonding/BondingManager.js
test/helpers/expectThrow.js
test/jobs/JobsManager.js

ManagerProxy now uses RETURNDATACOPY and RETURNDATASIZE opcodes to return dynamic length data from a target contract. As a result, we can use getter functions in BondingManager and JobsManager to return tuples rather than define a getter function for each individual field for a transcoder, delegator, job, claim, etc. We can also now directly retrieve streamId and transcodingOptions values directly from the JobsManager without relying on events. Using ethereumjs-testrpc v5.0.1@beta which includes the new opcodes. 
Closes #88

ManagerProxy returns dynamic length data

---

contracts/jobs/JobsManager.sol
contracts/jobs/libraries/JobLib.sol
migrations/5_init_protocol.js
migrations/migrations.config.js
package.json
test/unit/JobsManager.js
truffle.js

Current approach to restricting broadcaster deposit withdrawals:
The JobsManager keeps track of the number of active jobs for a broadcaster. A job can be in 3 states - `Active`, `Ended` and `Inactive`. When a job is created it becomes `Active`. When either a transcoder or broadcaster calls `endJob(jobId)` for a job, the job becomes `Ended` and an end block is set for the job. After a job's end block, it becomes `Inactive`. A broadcaster can only withdraw its deposit if it has 0 active jobs, and the latest end block for any of its ended jobs is less than or equal to the current block. A consequence of this is that a broadcaster must call `endJob` for all of its active jobs in order to withdraw its deposit which is not ideal from a UX/cost point of view, but let me know what you guys think. …

Restrictions on broadcaster withdrawals

---

contracts/jobs/JobsManager.sol
contracts/jobs/libraries/JobLib.sol
migrations/5_init_protocol.js
migrations/migrations.config.js
test/unit/JobsManager.js

Added a double claim segment slashing condition to prevent transcoders from claiming a segment more than once. Watchers can trigger this slashing condition and earn a finder's fee.
Triggering this slashing condition kicks out the transcoder and fully refunds a broadcaster for the job which I think makes sense. There needs to be some work done on the logic for the failed verification and missed verification slashing conditions which currently only refund a broadcaster for a claim, but also kick out the transcoder (meaning there are funds stuck in escrow) - I'll track that in a separate issue
Using `block.blockhash(claimBlock + 1)` for challenging segments - acknowledging the limitations of using this value and placing restrictions on the total length of the verification and slashing …

Double claim segment slashing condition. claimBlock + 1 for challenged segments

---

contracts/bonding/BondingManager.sol
contracts/jobs/JobsManager.sol
test/unit/BondingManager.js

A proposed solution for #115 
When a transcoder is slashed:
- The broadcaster is fully refunded for the job and all escrowed fees are returned
- The transcoder is removed from the active set and the total active set is reduced by the transcoder's active total stake
- The transcoder is removed from the transcoder pools
- Transcoder's delegators remain bonded
- As a result of the above, if the transcoder maintains a sufficient total stake (such that delegators do not delegate to someone else), it can rejoin the transcoder pools next round
The alternative was to implement a threshold such that a transcoder could trigger slashing conditions a certain number of times before it is actually slashed, but that would require additional state management and complexity. This approach is imperfect, …

Slashing post conditions

---

contracts/bonding/BondingManager.sol
contracts/bonding/IBondingManager.sol
contracts/jobs/JobsManager.sol
contracts/test/BondingManagerMock.sol
contracts/test/JobsManagerMock.sol
test/unit/BondingManager.js
test/unit/JobsManager.js

This uses the block hash of job creation block + 1 as the pseudorandom seed for assigning a transcoder to a job instead of the block hash of job creation block - 1 (which is known ahead of time). A consequence of this jobs are not immediately assigned to a transcoder at the time of creation. Instead, transcoders have to watch for all job creation events and check off-chain which jobs should be assigned to them. Changes will need to be made in the client accordingly.
When calling `claimWork` for the first time for a job, the contract will verify that the caller should be assigned the job based on the block hash of job creation block + 1. Note that since we use `block.blockhash()` to get the block hash for a block, we are limited to the past 256 blocks which means that a transcoder must …

Use job creation block as psuedorandom seed for assigning a transcoder

---

contracts/Controller.sol
contracts/IController.sol
contracts/IManager.sol
contracts/Manager.sol
contracts/Migrations.sol
contracts/bonding/BondingManager.sol
contracts/bonding/IBondingManager.sol
contracts/bonding/libraries/TokenPools.sol
contracts/jobs/IJobsManager.sol
contracts/jobs/JobsManager.sol
contracts/rounds/IRoundsManager.sol
contracts/rounds/RoundsManager.sol
contracts/test/BondingManagerMock.sol
contracts/test/JobsManagerMock.sol
contracts/test/ManagerProxyTargetMockV1.sol
contracts/test/ManagerProxyTargetMockV2.sol
contracts/test/ManagerProxyTargetMockV3.sol
contracts/test/MinterMock.sol
contracts/test/RoundsManagerMock.sol
contracts/test/VerifiableMock.sol
contracts/test/VerifierMock.sol
contracts/token/IMinter.sol
contracts/token/LivepeerToken.sol
contracts/token/LivepeerTokenFaucet.sol
contracts/token/Minter.sol
contracts/verification/IVerifiable.sol
contracts/verification/IVerifier.sol
contracts/verification/IdentityVerifier.sol
contracts/verification/LivepeerVerifier.sol
contracts/verification/OraclizeVerifier.sol

- Added more events that I thought might be useful for a client interacting with the contracts
- Removed unnecessary bool returns values for state mutating functions. Since our convention is to fail hard and fail early by reverting transactions upon any type of error, bool return values are never useful. There are some cases that a bool return value might be useful even if we're reverting, but I don't believe there are any cases of that in our code right now.
- Removed the constructor and fallback function from LivepeerToken because they shouldn't be needed - no ETH can be sent to the contract if the fallback function is not payable and the fallback function is non-payable by default
Current list of events (excluding LivepeerVerifier and LivepeerToken):
ParameterUpdate
SetContract …

More events. Remove unnecessary bool return values

---

contracts/bonding/BondingManager.sol
contracts/rounds/IRoundsManager.sol
contracts/rounds/RoundsManager.sol
contracts/test/RoundsManagerMock.sol
migrations/3_deploy_contracts.js
migrations/migrations.config.js
test/unit/BondingManager.js
test/unit/RoundsManager.js

Added a lock period during a round during which transcoders cannot join the transcoder pool or change their rates. The lock period is calculated as a percentage of the round length.
Closes #62

Add a lock period during a round s.t. transcoders cannot change rates

---

contracts/token/Minter.sol
test/unit/Minter.js

Currently, in `minter.createReward`, we calculate the mintable reward portion as `(mintableAmount * fracNum) / fracDenom)`. In the extreme case, both `mintableAmount` and `fracNum` can be very large (an example being when there is a single transcoder that is capturing all of the inflationary rewards for a few rounds leading to both a large `mintableAmount` and `fracNum`). In this case, it is possible for `mintableAmount * fracNum` to overflow.
As a proposed fix, `minter.createReward` can instead compute the percentage points represented by `fracNum` and `fracDenom` as `(fracNum * PERC_DIVISOR) / fracDenom)`. Since `PERC_DIVISOR` is known to be a constant 10^6, the risk of overflow when computing `fracNum * PERC_DIVISOR)` is less than the risk of overflow when computing `mintableAmount * …

Compute percentage points first when computing reward

---

contracts/Manager.sol
contracts/bonding/BondingManager.sol
contracts/bonding/libraries/TokenPools.sol
contracts/jobs/JobsManager.sol
contracts/libraries/MathUtils.sol
contracts/rounds/RoundsManager.sol
contracts/test/BondingManagerMock.sol
contracts/test/LivepeerTokenMock.sol
contracts/test/MinterMock.sol
contracts/token/ILivepeerToken.sol
contracts/token/IMinter.sol
contracts/token/LivepeerToken.sol
contracts/token/Minter.sol
contracts/token/VariableSupplyToken.sol
migrations/2_deploy_libraries.js
test/unit/BondingManager.js
test/unit/Minter.js
test/unit/TestMathUtils.sol
test/unit/VariableSupplyToken.js

This PR removes the concept of a redistribution pool - previously, the Minter maintained a redistribution pool that contained slashed funds and unclaimable rewards/fees. Removing the redistribution pool simplifies some of the accounting logic in the protocol and also makes it easier to implement ETH based payments (we wouldn't have to keep track of a redistribution pool for LPT and a redistribution pool for ETH).
We originally sent unclaimable rewards/fees to the redistribution pool because if a delegator with `lastClaimTokenPoolsSharesRound = M` s.t. `M < currentRound` changes its delegation away from a transcoder in `currentRound` before the transcoder calls `reward` during `currentRound` or calls `distributeFees` for a job created in round `N` s.t. `M < N < currentRound`, its reward …

Remove redistribution pool. Track claimable stake for token pools

---

contracts/bonding/BondingManager.sol
contracts/bonding/IBondingManager.sol
contracts/jobs/JobsManager.sol
contracts/test/BondingManagerMock.sol
contracts/test/JobsManagerMock.sol
contracts/test/MinterMock.sol
contracts/token/IMinter.sol
contracts/token/Minter.sol
test/unit/BondingManager.js
test/unit/JobsManager.js
test/unit/Minter.js

This PR changes job deposits and fee payouts to be denominated in ETH rather than LPT.
Broadcasters now use the payable `deposit` function in JobsManager to make a ETH deposit to pay for transcode jobs. Similar to with LPT, all ETH is forwarded to the Minter, which is the interim owner of all funds in the protocol until they are paid out.

Use ETH for job deposits and fee payments

---

Dockerfile-test
contracts/Controller.sol
contracts/IController.sol
migrations/3_deploy_contracts.js
package-lock.json
package.json
test/helpers/fixture.js
test/unit/BondingManager.js
test/unit/Controller.js

Proposing the use of the SHA1 hash of the head git commit at the time of deployment as the version identifier for contracts. The Controller would store a contract's address in addition to the Git commit hash at the time of contract deployment. 
Ex.
If we deploy an updated version of the BondingManager contract, we can examine the Git commit hash associated with the contract id `keccak256("BondingManagerTarget")` to determine what version of the target contract that the proxy contract is using.
I thought using this hash as a version identifier would be more meaningful since serve as a direct reference in the Git repository - I don't immediately see a need for an additional version string besides this, but open to thoughts.

Add git commit hash as version identifier to contract info in Controller

---

contracts/token/Minter.sol
contracts/verification/LivepeerVerifier.sol
migrations/migrations.config.js
test/integration/Delegation.js
test/unit/Minter.js
truffle.js
verification_test/LivepeerVerifier.js

- Setter for inflation change
- Setter for adding solvers to LivepeerVerifier
- Fix LivepeerVerifier tests
- Tweak initial parameters for test deployments

Inflation change and verifier solver setters. Tweak initial parameters

---

contracts/test/GenericMock.sol
test/unit/GenesisManager.js

- GenericMock contract that is meant to be used for mocking out any return values that a contract depends on from another contract. Ideally, we can switch to using this in all of our tests once I tweak it a little more rather than having a bunch of different mock contracts
- GenesisManager unit test
Integration test for genesis state to come separately

GenesisManager unit test

---

contracts/bonding/BondingManager.sol
contracts/bonding/IBondingManager.sol
contracts/jobs/JobsManager.sol
contracts/jobs/libraries/JobLib.sol
contracts/rounds/AdjustableRoundsManager.sol
contracts/rounds/IRoundsManager.sol
contracts/rounds/RoundsManager.sol
contracts/test/BondingManagerMock.sol
contracts/test/GenericMock.sol
contracts/test/RoundsManagerMock.sol
package.json
test/integration/JobAssignment.js
test/unit/JobsManager.js
test/unit/RoundsManager.js

Fixes #147 
Implements solution #3 described in the issue. The Go client will require a small change to pass in the job creation block hash instead of the job creation block number as well. Includes an integration test for job assignment (the test might be flaky sometimes because it runs a bunch of trials and computes the percentage of assigned jobs for each transcoder and compares the computed percentage against the expected percentage with some acceptable delta)

Fix job assignment

---

contracts/bonding/BondingManager.sol
contracts/jobs/JobsManager.sol
contracts/test/GenericMock.sol
test/unit/BondingManager.js

Fixes #146 
A user that wants to register as a transcoder must delegate to themselves and have non-zero bonded stake before registering. This ensures that transcoders always have something at stake which is especially important right now since only transcoders are slashed for faults at the moment. 
As a result of this change, transcoders that unbond now also automatically resign as a registered transcoder. In the future, if we implement partial unbonding we could update the logic to automatically resign a registered transcoder once it unbonds all of its stake. This change also serves as a solution to the current issue where a transcoder's cut of rewards and fees can be lost if a transcoder is unbonded, but still registered.

Enforce transcoders to be self-bonded

---

package.json
utils/contractDeployer.js

Using `git rev-parse HEAD` to get head commit hash instead, as suggested by @j0sh in #152

Remove nodegit from contract deployer

---

utils/contractDeployer.js

Apparently CircleCI doesn't do builds for pull requests based on forks so didn't catch this until after the change was merged in :(

Remove trailing newline from commit hash

---

contracts/bonding/BondingManager.sol
contracts/bonding/IBondingManager.sol
contracts/jobs/JobsManager.sol
contracts/rounds/AdjustableRoundsManager.sol
contracts/test/BondingManagerMock.sol
migrations/3_deploy_contracts.js
test/integration/DoubleClaimSegmentSlashing.js
test/integration/FailedVerificationSlashing.js
test/integration/MissedVerificationSlashing.js
test/integration/SlashingEdgeCases.js

Closes #162 
Addresses the two problems mentioned in the issue. Added integration tests for each slashing condition in: `FailedVerificationSlashing.js`, `MissedVerificationSlashing.js` and `DoubleClaimSegmentSlashing.js`. Also added `SlashingEdgeCases.js` that tests that the bugs/exploits described in the issue are fixed - there is one test for slashing a transcoder after it has unbonded and resigned and one test for slashing a transcoder after it has already been slashed because it committed another fault (the scenario used in the test is the transcoder first double claims segments, is slashed and then misses verification for a subsequent transcode claim). Additional clarifying comments made in-line.

Slashing fixes with accompanying tests

---

.gitattributes
contracts/rounds/IRoundsManager.sol
contracts/rounds/RoundsManager.sol
migrations/3_deploy_contracts.js
package-lock.json
package.json
test/unit/RoundsManager.js
test/unit/helpers/Fixture.js

Fixes #160 
Makes sure that the roundLength parameter can be updated properly - previously if we increased roundLength, we would end up with duplicate round numbers. Also refactored RoundsManager to improve path coverage. It is now using a unit test fixture that uses the GenericMock contract to stub out the rest of the contract dependencies. The goal is to move all our unit tests to this architecture, with the RoundsManager unit test being the first one to move over and the plan is to move the rest of the unit tests over in separate PRs. Additional comments in-line

Ensure roundLength can be increased/decreased

---

contracts/jobs/JobsManager.sol
test/unit/JobsManager.js

Fixes #175 
As described in the issue, the minor downside to the approach taken in this PR is that it removes the previous invariant: a broadcaster cannot withdraw its deposit if it has any active jobs. If a job is set as inactive by setting its end block to the current block when the job's transcoder is slashed, the contract does not maintain enough state (and ideally shouldn't have to) to also update the broadcaster's withdraw block to reflect the possibility that the broadcaster no longer has any active jobs. As a result, the restriction is no longer that a broadcaster cannot withdraw its deposit if it has any active jobs since a broadcaster might not be able to withdraw even if it does not have any active jobs. The rules for withdrawal are now:
-  A broadcaster commits to keeping a …

Set jobs as inactive when a transcoder is slashed

---

contracts/bonding/BondingManager.sol
contracts/jobs/JobsManager.sol
contracts/test/BondingManagerMock.sol
contracts/test/GenericMock.sol
contracts/test/JobsManagerMock.sol
contracts/test/MinterMock.sol
contracts/token/IMinter.sol
contracts/token/Minter.sol
test/unit/Minter.js

Fixes #171 
Also label ETH and token transfer functions in the Minter that always trust their caller as "trusted".

Upgradeable Minter with additional tests

---

contracts/bonding/BondingManager.sol
test/unit/BondingManager.js

Fixes #188 
This implements the ability for registered transcoders to price match the lowest price set by any registered transcoder during the round lock period.

Transcoder price matching with a price floor during round lock period

---

contracts/jobs/JobsManager.sol
contracts/jobs/libraries/JobLib.sol
migrations/3_deploy_contracts.js
migrations/migrations.config.js
test/integration/JobAssignment.js
test/unit/JobsManager.js

Fixes #176 
Fixes #169 
Changes the `slashingPeriod` parameter to `verificationSlashingPeriod` to make it more clear that this parameter defines the length of the slashing period specifically for verification related faults (i.e. missed verification) and to eliminate any potential confusion with regards to when slashing can happen (slashing for non-verification related faults like double claiming segments can occur at any time).

Minor JobsManager fixes

---

contracts/bonding/BondingManager.sol
contracts/bonding/IBondingManager.sol
test/unit/BondingManager.js

Closes #191 
Allows a user campaigning to become a transcoder to still invoke `transcoder` to set rewardCut, feeShare and pricePerSegment even if the transcoder pool is full and they do not have sufficient delegated stake to join the pool

Allow transcoders with insufficient delegated stake to set rewardCut, feeShare, price

---

migrations/4_genesis.js
migrations/genesis.config.js
scripts/getVestingContracts.js
scripts/validateDeploymentAndGenesis.js

- Fix calculation of `grantsStartTimestamp` in migration scripts
- Fix checks in post deployment script for grants
- Process grants in sequence in migration scripts
- Better printing of grant addresses
- Update `timeToGrantsStart` parameter in `migrations/genesis.config.js`

Small deployment related fixes

---

contracts/bonding/BondingManager.sol
test/integration/Delegation.js
test/integration/SystemPause.js
test/unit/BondingManager.js

- Restrict transcoders from delegating toward other transcoders
- Update accounting in `unbond()` to always reduce delegated stake if delegate is a registered transcoder

Disallow transcoders delegating toward other transcoders

---

contracts/ServiceRegistry.sol
migrations/3_deploy_contracts.js
test/integration/JobAssignment.js
test/unit/ServiceRegistry.js

Implementation for LIP-9: https://github.com/livepeer/LIPs/blob/master/LIPs/LIP-9.md

Implement LIP-9: Service Registry

---

contracts/bonding/BondingManager.sol
contracts/bonding/IBondingManager.sol
test/unit/BondingManager.js

Implementation for [LIP-11](https://github.com/livepeer/LIPs/blob/master/LIPs/LIP-11.md).
Note: Decided to use the name `bondedAmount` instead of `delegationAmount` (which is used in the spec) for the `Bond()` event signature because it feels clearer - the value should reflect the delegator's current bonded amount at the end of the state transition execution of the `bond()` function.

Implement LIP-11: Bond Event Details

---

contracts/bonding/IBondingManager.sol
package.json
scripts/run_ganache.sh
test/integration/RoundInitialization.js

- Add comments to `IBondingManager.sol` to document deprecated events and the event signatures that can be used to construct the appropriate topic hashes to filter for past logs corresponding to the deprecated events
- Add an integration test for round initialization with test cases involving various various values for `numActiveTranscoders` and `numTranscoders`

Deprecated event comments and round initialization integration test

---

contracts/bonding/BondingManager.sol
test/unit/BondingManager.js

- Keep track of a delegator's current delegate prior to fully unbonding so that the `Unbond` event can be emitted with the tracked delegate address (as opposed to the current behavior of emitting the event with the null address). Fixes #232 
- Add unit tests for the fields included in the `Unbond` event when partial unbonding and fully unbonding.

Emit correct delegate address in Unbond event when fully unbonding

---

contracts/pm/ERC20TicketBroker.sol
contracts/pm/ETHTicketBroker.sol
contracts/pm/LivepeerETHTicketBroker.sol
contracts/pm/TicketBroker.sol
test/unit/LivepeerETHTicketBroker.js
test/unit/TicketBroker.js

- Add fundAndApproveSigners() function to wrap funding deposit and penalty escrow and approving signers
- Add test for separation of ticket redeemer and recipient

PM: fundAndApproveSigners() wrapper 

---

contracts/pm/ERC20TicketBroker.sol
contracts/pm/ETHTicketBroker.sol
contracts/pm/LivepeerETHTicketBroker.sol
contracts/pm/TicketBroker.sol
test/unit/LivepeerETHTicketBroker.js
test/unit/TicketBroker.js

Implements signer approval by a sender.
This PR does not implement signer revocation by a sender which can be addressed separately. See #252 for more details.

PM: Allow sender to approve signers

---

contracts/pm/ERC20TicketBroker.sol
contracts/pm/ETHTicketBroker.sol
contracts/pm/LivepeerETHTicketBroker.sol
contracts/pm/TicketBroker.sol
test/unit/LivepeerETHTicketBroker.js

So far we've used two different approaches for reusing code from
`TicketBroker` in its subtypes: one where only subtypes implement
functions and use modifiers to reuse `TicketBroker`'s flow of
requirements and accounting, and another approach where `TicketBroker`
implements a public/external function that contains the entire flow,
and calls an abstract method that each subtype implements according to
their needs.
The first approach (using modifiers) resulted in code duplication, i.e.
having to use the exact same modifiers in more than one contract, which
also resulted in duplicate test code.
To get out of this code duplication we're refactoring to the second
approach across the board.
The main cost is the complication introduced in the ERC20 implementation,
but since it's just an example …

PM: TicketBroker inheritance refactor

---

contracts/pm/ERC20TicketBroker.sol
contracts/pm/ETHTicketBroker.sol
contracts/pm/LivepeerETHTicketBroker.sol
contracts/pm/TicketBroker.sol
migrations/3_deploy_contracts.js
migrations/migrations.config.js
test/unit/LivepeerETHTicketBroker.js
test/unit/TicketBroker.js

We decided to create a separate param for the signer revocation delay
to decouple this concern from the `unlockPeriod`.
The reason we need a delayed revocation in the first place, is to allow
receivers of tickets to become aware of a pending revocation and make
sure they cash in any tickets signed by the soon-to-be-revoked signer
before those tickets become invalid.

PM: senders can revoke signers

---

contracts/pm/LivepeerETHTicketBroker.sol
test/unit/LivepeerETHTicketBroker.js

Remove ticket expiration from LivepeerETHTicketBroker for MVS:
Note: The ticket data structure still contains the `auxData` field which is also used when generating the ticket hash. After this PR, LivepeerETHTicketBroker will not parse the field to execute a validation check, but the field will still be a part of the ticket.
See #267 for more background discussion and this [comment](https://github.com/livepeer/protocol/issues/267#issuecomment-449189086) for the currently proposed roadmap for the ticket expiration feature.

pm: remove LivepeerETHTicketBroker ticket expiration for MVS

---

contracts/pm/TicketBroker.sol
test/helpers/ticket.js
test/integration/TicketFlow.js
test/unit/LivepeerETHTicketBroker.js
test/unit/TicketBroker.js

Temporarily using individual struct fields as params instead of a ticket struct
in redeemWinningTicket() because the Go abigen tool for creating Go
specific contract bindings currently does not support struct params.

pm: Temporarily Remove ticket struct param

---

contracts/pm/TicketBroker.sol
contracts/pm/mixins/MixinTicketBrokerCore.sol
contracts/pm/mixins/MixinWrappers.sol
contracts/pm/mixins/interfaces/MTicketBrokerCore.sol
test/unit/TicketBroker.js

Closes #274 
`batchRedeemWinningTickets()` uses the `redeemWinningTicketNoRevert()` helper to redeem tickets without reverting the entire function when execution hits a revert in the underlying call. 
This PR does not implement the suggestion in #274 of validating each ticket, summing the face values of the tickets and then executing a single batch value transfer which would save some gas. Instead, each ticket redemption is distinct and involves its own associated value transfer. I chose to do this to keep things simple initially. Furthermore, in a Livepeer context, the value transfer involves sending the value to the recipient's (orchestrator) fee pool for the ticket's creation round and in cases where a batch of tickets have different creation rounds, there would need to be a separate …

pm: Batch ticket redemption

---

contracts/pm/TicketBroker.sol
contracts/pm/mixins/MixinTicketBrokerCore.sol
contracts/pm/mixins/MixinTicketProcessor.sol
contracts/pm/mixins/MixinWrappers.sol
contracts/pm/mixins/interfaces/MTicketBrokerCore.sol
contracts/pm/mixins/interfaces/MTicketProcessor.sol
contracts/rounds/IRoundsManager.sol
contracts/rounds/RoundsManager.sol
migrations/3_deploy_contracts.js
migrations/migrations.config.js
test/helpers/ticket.js
test/integration/TicketFlow.js
test/unit/RoundsManager.js
test/unit/TicketBroker.js

Closes #281 via dfa2512
Closes #282 via 4306cd3
Also removed a now unneeded wrapper function in `ticket.js` because we have switched back to passing the `Ticket` struct into `redeemWinningTicket()` instead of passing in the individual `Ticket` fields

pm: ticket expiration validation

---

contracts/pm/mixins/MixinReserve.sol
contracts/pm/mixins/MixinTicketBrokerCore.sol
contracts/pm/mixins/interfaces/MReserve.sol
test/integration/TicketFlow.js
test/unit/TicketBroker.js

Adds the `getSenderInfo()` getter which returns both sender info and relevant info for the sender's reserve in a single contract call request.

pm: getSenderInfo() getter with both sender & reserve info

---

contracts/pm/mixins/MixinReserve.sol
test/unit/TicketBroker.js

Implements a method `claimableReserve(address _claimaint, address _reserveHolder) returns (uint256 claimableReserve)` in `MixinReserve.sol` which returns the amount of funds claimable by a claimant/orchestrator from a reserveHolder/broadcaster's reserve
Added unit tests for the added method 
**Additional Information (TODO)**
* At the moment we do not check if the claimant is actually registered as orchestrator in the current round (if the reserveHolder's reserve is not frozen) or that the claimant was/is registered as orchestrator during the freezeRound in case a reserveHolder's reserve has been frozen. 
This is due to the corresponding functionality not being …

pm: claimableReserve function & tests

---

contracts/bonding/BondingManager.sol
contracts/bonding/IBondingManager.sol
package-lock.json
test/helpers/expectFail.js
test/integration/Delegation.js
test/integration/Rewards.js
test/integration/RoundInitialization.js
test/integration/SystemPause.js
test/integration/TicketFlow.js
test/unit/BondingManager.js
test/unit/TicketBroker.js

_Note: I created a new branch for the project in which we can merge the incoming PRs. The `expand-active-transcoder-set` branch is branched from the `pm` branch._
This PR removes all `pricePerSegment`, `pendingPricePerSegment` and `electTranscoder()` references and usage from the `BondingManager` contract.
Price discovery and transcoder selection now happens off-chain. 
- Deprecated `pricePerSegment` and `pendingPricePerSegment` variables on the `Transcoder` struct to not change the storage layout of the contract
- Removed `electTranscoder()` method from the `BondingManager` contract and interface
- Removed all state updates pertaining to `pricePerSegment` and `pendingPricePerSegment` in …

bondingmanager: remove pricePerSegment and transcoderElection

---

contracts/pm/mixins/MixinReserve.sol
contracts/pm/mixins/MixinTicketBrokerCore.sol
contracts/pm/mixins/interfaces/MTicketBrokerCore.sol
test/helpers/ticket.js
test/integration/BroadcasterWithdrawalFlow.js
test/unit/TicketBroker.js

This PR updates the unlock period to be round based which makes the unlock period consistent with other time based variables in the rest of the contracts. Furthermore, the addition of a `withdrawRound` for the sender allows us to prevent reserve claims after the sender's unlock period is over which avoids an edge case with a reserve's `claimedForRound` and `claimedByAddress` mappings not being cleared upon withdrawal round N and being non-zero after a funding operation in that same round.

pm: Change unlock period to be round based

---

contracts/pm/TicketBroker.sol
contracts/pm/mixins/MixinReserve.sol
contracts/pm/mixins/MixinTicketBrokerCore.sol
contracts/pm/mixins/interfaces/MReserve.sol
contracts/pm/mixins/interfaces/MTicketBrokerCore.sol
migrations/3_deploy_contracts.js
migrations/migrations.config.js
test/helpers/ticket.js
test/integration/BroadcasterWithdrawalFlow.js
test/unit/TicketBroker.js

This PR removes the freeze period from the TicketBroker contract. Instead of freezing the reserve for multiple rounds after the deposit is depleted, recipients in the active set can claim from the reserve up to their max allocation for the remainder of the round. At the beginning of the next round, the max allocation for each recipient in the active set in the round is calculated based on the reserve funds available at the beginning of the round.
Fixes #306 
See the below Discord conversation for additional context:
```
j0sh: The freeze period removal makes sense to me. Just want to clarify my own understanding on one point:
The original concern I had (the reason for re-reviewing things) was due to the fact that tickets could be valid for longer than a round, so if the reserve is "reset" …
```

Remove freeze period

---

contracts/Manager.sol
contracts/pm/mixins/MixinContractRegistry.sol
contracts/pm/mixins/MixinTicketBrokerCore.sol
contracts/pm/mixins/MixinWrappers.sol
contracts/pm/mixins/interfaces/MContractRegistry.sol
test/unit/BondingManager.js
test/unit/RoundsManager.js
test/unit/TicketBroker.js

This PR adds a modifier to external/public `TicketBroker` functions and disallows ticket redemption if the round is not initialized.
- Moved all external/public state mutating functions in the `pm` package to `TicketBroker.sol` so we can use `Manager.whenSystemNotPaused`. 
- Added `currentRoundInitialized` modifier to `TicketBroker`
- Add `whenSystemNotPaused` modifier to all external/public functions
- Add `currentRountInitialized` modifier to `redeemWinningTicket` and `batchRedeemWinningTickets`
- Added a revert message for `Manager.whenSystemNotPaused`
Adjusted & ran unit and integation tests
**Does this pull request close any open …

pm: add whenSystemNotPaused and currentRoundInitialized modifiers

---

contracts/bonding/BondingManager.sol
contracts/bonding/IBondingManager.sol
test/unit/BondingManager.js

This PR adds an `EarningsClaimed` event to the `BondingManager` that will be emitted when a delegator claims earnings. 
```
event EarningsClaimed(address indexed delegator, address indexed delegate, uint256 rewards, uint256 fees, uint256 startRound, uint256 endRound);
```
- added `EarningsClaimed` event definition to `BondingManager` interface
- emit `EarningsClaimed` event from `updateDelegatorWithEarnings`
- add unit tests to check if the event gets emitted correctly
Adjusted & ran unit and integation tests
**Does this pull request close any open issues?**
Fixes #305 
**Checklist:**

bonding: EarningsClaimed event

---

contracts/bonding/BondingManager.sol
test/unit/BondingManager.js

This PR replaces `onlyTicketBroker` with a newly introduced `onlyVerifier` modifier
- added an `onlyVerifier` modifier that checks if the caller is the `Verifier` contract (0x000...) in streamflow
- replace `onlyTicketBroker` with `onlyVerifier` on `bondingManager.slashTranscoder()`
- adjust `slashTranscoder` unit tests in `BondingManager.js` to call from the mock verifier instead of ticketBroker
Adjusted & ran unit and integration tests
**Does this pull request close any open issues?**
Fixes #315 
**Checklist:**

bonding: onlyVerifier modifier for slashTranscoder()

---

README.md

This PR fixes a broken link to the truffle docs in `README.md`
Fixes #332

readme: fix truffle docs link

---

contracts/bonding/IBondingManager.sol
contracts/pm/mixins/MixinReserve.sol
test/unit/TicketBroker.js

This PR updates the `TicketBroker` to use `BondingManager.isActiveTranscoder()` instead of `BondingManager.isRegisteredTranscoder()` when calculating the claimable amount from a sender's reserve. This change will ensure that only active transcoders in the current round can claim from a sender's reserve which is the desired behavior because a sender's reserve should be committed to the members of the active set in the current round. Previously, `TicketBroker` was only checking if the claimant was a registered transcoder which was insufficient.
Fixes #339

pm: Use isActiveTranscoder() when claiming from reserve

---

contracts/bonding/BondingManager.sol
test/integration/Delegation.js
test/unit/BondingManager.js

This PR updates `BondingManager.getTotalBonded()` to return `currentRoundTotalActiveStake` instead of iterating through the current members of the transcoder pool. This change saves gas during round initialization - instead of using N SLOADs (where N is the size of the pool) `getTotalBonded()` uses a single SLOAD because `currentRoundTotalActiveStake` would have been already set by the call to `BondingManager.setCurrentRoundTotalActiveStake()` earlier during round initialization.
Fixes #334

bonding: Return current total active stake in getTotalBonded()

---

contracts/bonding/BondingManager.sol
contracts/bonding/IBondingManager.sol
test/unit/BondingManager.js

This PR updates some contract events related to the transcoder with semantics that better fit the BondingManager update from #323 
- removed `registered` argument from `TranscoderUpdate` event
- added a `TranscoderActivated` event when a transcoder gets inserted into the pool and is set to become active for the next round
- added a `TranscoderDeactivated` event, replacing both `TranscoderResigned` and `TranscoderEvicted`
adjusted & ran test suite
**Checklist:**

bonding: transcoder event changes

---

contracts/Manager.sol
contracts/bonding/BondingManager.sol
contracts/libraries/SortedDoublyLL.sol
contracts/rounds/RoundsManager.sol
test/helpers/expectFail.js
test/unit/BondingManager.js
test/unit/RoundsManager.js

This PR adds revert reasons to the require statements for the upgradeable contracts.
_NOTE:_ tests that use a `GenerickMock.sol` contract to execute methods in unit tests don't return revert reasons yet, see #333. 
_NOTE:_ `public view` functions seem to not return revert reasons as they are calls and not transactions.
Adjusted & ran unit and integation tests
**Does this pull request close any open issues?**
Fixes #313 
**Checklist:**

bonding, rounds: revert reasons

---

contracts/pm/mixins/MixinTicketProcessor.sol
contracts/test/mocks/MinterMock.sol
contracts/token/IMinter.sol
contracts/token/Minter.sol
migrations/3_deploy_contracts.js
test/integration/BroadcasterWithdrawalFlow.js
test/integration/TicketFlow.js
test/unit/Minter.js
test/unit/helpers/Fixture.js
utils/contractDeployer.js

This PR reverts changes in the Minter to logically match the mainnet implementation (excluding compiler version, revert reasons, etc.). One thing to note is that contracts will use the JobsManager contract ID to interact with the TicketBroker.
Fixes #347

Revert Minter changes to match mainnet implementation

---

test/unit/BondingManager.js

This PR allows the `GenerickMock.execute` method that makes external contract calls to return revert reasons. It also updates any unit tests that use this method to call a function on another contract with the right permissions to test for revert reasons.
Fixes #333

test: mock proxy revert reasons

---

contracts/Controller.sol
contracts/Manager.sol
contracts/ManagerProxy.sol
contracts/ManagerProxyTarget.sol
contracts/ServiceRegistry.sol
contracts/bonding/BondingManager.sol
contracts/bonding/IBondingManager.sol
contracts/libraries/MathUtils.sol
contracts/libraries/SortedDoublyLL.sol
contracts/pm/TicketBroker.sol
contracts/pm/mixins/MixinContractRegistry.sol
contracts/pm/mixins/MixinTicketBrokerCore.sol
contracts/pm/mixins/MixinWrappers.sol
contracts/pm/mixins/interfaces/MReserve.sol
contracts/rounds/RoundsManager.sol
contracts/test/mocks/GenericMock.sol
contracts/token/LivepeerTokenFaucet.sol
contracts/token/Minter.sol
contracts/token/VariableSupplyToken.sol

This PR adds proper NATSPEC comment formatting to all contracts.
- Changed some minor semantic details in BondingManager.js
- Changed most `@dev` tags to `@notice` to distinguish end-user description from extra developer comments
Fixes #130

NATSPEC comments

---

.circleci/config.yml
README.md
contracts/ManagerProxy.sol
contracts/bonding/BondingManager.sol
contracts/pm/TicketBroker.sol
contracts/pm/mixins/MixinContractRegistry.sol
contracts/pm/mixins/MixinTicketBrokerCore.sol
contracts/rounds/RoundsManager.sol
package-lock.json
package.json
test/gas-report/redeemTicket.js
test/integration/TicketFrontRun.js
test/unit/TicketBroker.js

This PR implements a few fixes related to the external security audit. 
Summary of changes:
- Make `getTicketHash()` public so that off-chain hashing implementations can be more easily checked against the output from the EVM
- Add a gas report test for redeeming winning tickets
- Use Node v10.17.0 and upgrade a few dependencies
- Add some notes in the README about ABIEncoderV2 usage and ERC20 functions
- Add comments about calling setters for upgradeable contracts as well as shadowed functions in ManagerProxy
- Add an integration test demonstrating that honest transcoders are protected against ticket front running scenarios as long as they don't hold on to more value than their reserve allocation
See the commit log for more details.

Various audit fixes

---

contracts/bonding/BondingManager.sol
test/unit/BondingManager.js

This PR moves emitting the `EarningsClaimed` event in `updateDelegatorWithearnings()` outside of the conditional so that it gets fired even if the delegator has no delegate. 
This prevents indexers from ending up with stale data.
Fixes #360

bonding: move EarningsClaimed event

---

contracts/bonding/BondingManager.sol
test/unit/BondingManager.js

This PR removes the require statements in `BondingManager.pendingStake()` and `BondingManager.pendingFees()`. Instead of validating the `_endRound` argument using a require statement, both functions will now execute pending stake/fee calculations through the current round if `_endRound > currentRound`. If the `_endRound <= delegator.lastClaimRound`, the loop that executes the calculations will not run and `pendingStake()` will return `delegator.bondedAmount` and `pendingFees()` will return `delegator.fees`.
Fixes #363

bonding: Remove require in pendingStake() and pendingFees()

---

contracts/refund/IAlphaJobsManager.sol
contracts/refund/Refunder.sol
contracts/test/mocks/AlphaJobsManagerMock.sol
test/unit/Refunder.js

This PR adds a `Refunder` contract that reads the state of deposits in the `JobsManager` contract in order to determine the amount that an address is eligible to withdraw.
- The `Refunder` receives ETH via its fallback function. The total amount sent to the `Refunder` will be the sum of all outstanding deposits managed by the `JobsManager`
- The `withdraw()` function accepts an address as an argument. So, a third party address can submit the `withdraw()` call for another address
- If the provided address does not have a deposit with the `JobsManager`, the tx will revert
- If the provided address has already withdrawn its refund, the tx will revert
See the [upgrade plan](https://gist.github.com/yondonfu/c87756debb08d7839105c9bbece709c7) for more details on how the `Refunder` contract will …

Add Refunder contract
